### ISSUE TITLE
Magical Crops support broken

### ISSUE THREAD

**Issue by ghost** [BuildCraft/BuildcraftCompat#68]
Buildcraft Compat 7.1.5

The harvester robots actually destroy the crop instead of leaving it and only dropping the respective Essence. This makes them useless as for some reason you don't even get your invested seed back, but just the Essence drop. You do get some seeds back from MagicalCrops' configurable chance for a 2nd seed drop it seems.

**Comment by AlexIIL** [comment]
I think @tmoore79 implemented this in #64, can you check if you can easily fix this?

**Comment by Morebits05** [comment]
I've still got the code, it uses the witchery code.
See: https://github.com/BuildCraft/BuildcraftCompat/blob/7.1.x/common/buildcraft/compat/witchery/CropHandlerWitchery.java

and here's my code:
https://github.com/BuildCraft/BuildcraftCompat/blob/7.1.x/common/buildcraft/compat/magiccrops/CropHandlerMagicCrops.java

Now I see the error, yeh I didn't implement that! When i used it for Project Ozone, I had a planter plant some more seeds, from the chest, since the version didnt use Agricraft Crops Sticks.

**Comment by asiekierka** [comment]
Technically an enhancement as the behaviour did not exist previously.
